vim.keymap.set("n", "<Leader>o", require("nvim-tree.api").tree.toggle)
vim.keymap.set("n", "<Leader>e", require("nvim-tree.api").tree.focus)
vim.keymap.set("n", "<Leader>fw", require("telescope.builtin").live_grep)
vim.keymap.set("n", "<Leader>ff", require("telescope.builtin").find_files)
vim.keymap.set("n", "<Leader>up", vim.pack.update)
vim.keymap.set("n", "<Leader>tt", ":Themery<CR>")
vim.keymap.set("n", "<Leader>tf", ":ToggleTerm<CR>")
vim.keymap.set("n", "<A-Right>", ":BufferLineCycleNext<CR>", { silent = true })
vim.keymap.set("n", "<A-Left>", ":BufferLineCyclePrev<CR>", { silent = true })
vim.keymap.set("n", "<leader>la", vim.lsp.buf.code_action, { silent = true })
vim.keymap.set("n", "<leader>ld", vim.lsp.buf.workspace_diagnostics, { silent = true })
