local mini_files = require("mini.files")
vim.keymap.set("n", "<Leader>e", mini_files.open)
vim.keymap.set("n", "<Leader>fw", require("telescope.builtin").live_grep)
vim.keymap.set("n", "<Leader>ff", require("telescope.builtin").find_files)
vim.keymap.set("n", "<Leader>up", vim.pack.update)
vim.keymap.set("n", "<Leader>tt", ":Themery<CR>")
vim.keymap.set("n", "<Leader>tf", ":ToggleTerm<CR>")
vim.keymap.set("n", "<A-Right>", ":bnext<CR>", { silent = true })
vim.keymap.set("n", "<A-Left>", ":bprev<CR>", { silent = true })
vim.keymap.set("n", "<leader>la", vim.lsp.buf.code_action, { silent = true })
vim.keymap.set("n", "<leader>ld", vim.diagnostic.open_float, { silent = true })
vim.keymap.set("n", "gd", vim.lsp.buf.definition)
vim.keymap.set("n", "<Enter>", function()
	mini_files.go_in({ close_on_file = true })
end, { silent = true })
